version: '3.11'

services:
  db:
    image: postgres
    env_file:
      - .env
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web interface

  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - mailhog